modLoader="javafml" #mandatory
loaderVersion="[37,)" #mandatory
issueTrackerURL="https://github.com/itsmeow/betteranimalsplus/issues" #optional
displayURL="https://betteranimalsplus.com/" #optional
logoFile="icon.png" #optional
credits="Cybercat5555: Design, Modeling, Texturing, Ideas; its_meow: Programming, AI, Functionality, Ideas; Wolverbyte: Design, Modeling, Texturing, Ideas" #optional
authors="cybercat5555, itsmeowdev, Wolverbyte" #optional
license="CC BY-NC-SA 4.0 https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode"
[[mods]] #mandatory
modId="betteranimalsplus" #mandatory
version="${version}" #mandatory
displayName="Better Animals Plus" #mandatory
# The description text for the mod (multi line!) (#mandatory)
description='''
~Breathing new life into your worlds~
Adds 35+ new animals to your world, with items, food, blocks, and armor to supplement them.'''
[[dependencies.betteranimalsplus]]
    modId="forge"
    mandatory=true
    versionRange="[37.1.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.betteranimalsplus]]
    modId="architectury"
    mandatory=true
    versionRange="[2.8.0,)"
    ordering="NONE"
    side="BOTH"